# PUPNET DEPLOY: 1.10.0
# Use: 'pupnet --help conf' for information.

# APP PREAMBLE
AppBaseName = HelloWorld
AppFriendlyName = Hello World
AppId = com.example.helloworld
AppVersionRelease = 1.0.0[1]
AppShortSummary = A HelloWorld application
AppDescription = """
    HelloWorld is a really friendly application.
    It says "Hello" and supports an additional "Goodbye" feature.
    
    It is the only app you'll ever need.
"""
AppLicenseId = LicenseRef-Proprietary
AppLicenseFile = 
AppChangeFile = 

# PUBLISHER
PublisherName = The Hello World Team
PublisherId = com.example
PublisherCopyright = Copyright (C) Hello World Team 2025
PublisherLinkName = Home Page
PublisherLinkUrl = 
PublisherEmail = 
PublisherGpgKeyId = 

# DESKTOP INTEGRATION
DesktopNoDisplay = false
DesktopTerminal = true
DesktopFile = 
StartCommand = 
PrimeCategory = 
MetaFile = 
IconFiles = 

# DOTNET PUBLISH
DotnetProjectPath = 
DotnetPublishArgs = -p:Version=${APP_VERSION} --self-contained true -p:DebugType=None -p:DebugSymbols=false
DotnetPostPublish = 
DotnetPostPublishOnWindows = 

# PACKAGE OUTPUT
PackageName = HelloWorld
OutputDirectory = Deploy/OUT

# APPIMAGE OPTIONS
AppImageArgs = 
AppImageRuntimePath = 
AppImageVersionOutput = false

# FLATPAK OPTIONS
FlatpakPlatformRuntime = org.freedesktop.Platform
FlatpakPlatformSdk = org.freedesktop.Sdk
FlatpakPlatformVersion = 25.08
FlatpakFinishArgs = """
    --socket=x11
"""
FlatpakBuilderArgs = 

# RPM OPTIONS
RpmAutoReq = false
RpmAutoProv = true
RpmRequires = """
    glibc
    libgcc
    ca-certificates
    openssl-libs
    libstdc++
    libicu
    tzdata
    krb5-libs
"""

# DEBIAN OPTIONS
DebianRecommends = """
    libc6
    libgcc-s1
    libgssapi-krb5-2
    libicu72
    libssl3
    libstdc++6
    zlib1g
"""

# WINDOWS SETUP OPTIONS
SetupGroupName = 
SetupAdminInstall = false
SetupCommandPrompt = 
SetupMinWindowsVersion = 10
SetupSignTool = 
SetupSuffixOutput = 
SetupVersionOutput = false
SetupUninstallScript = 

# ZIP OPTIONS
ZipVersionOutput = true